# Change the name of the DB to `database` to use it.
# Eg `mysql` -> `database`
# Do not change the name of the adapter.
# Be sure to uncomment the adapter in the Gemfile as well!
postgres:
  adapter: postgres
  host: localhost
  user: usernmae
  database: asq_queries
mysql:
  adapter: mysql2
  host: localhost
  user: username
  password: password
  database: asq_queries
  timeout: 30
  reconnect: true
sqlite:
  adapter: sqlite
  database: asq_queries

login:
  user: 'root'
  pass: 'default'
misc:
  defaultDb: false # the DB that will be selected by default
  dblistMatch: false # bool false or string with regex to filter databases.