database:
  adapter: mysql2
  host: localhost
  user: root
  password: root
  database: asq_queries
  timeout: 30
  reconnect: true
login:
  user: 'root'
  pass: 'default'
misc:
  defaultDb: false # the DB that will be selected by default
  dblistMatch: false # bool false or string with regex to filter databases.