# Comment out the DB adapters you don't want to use,
# and vice versa for the one you want to use.
database:
  adapter: mysql2
  host: localhost
  user: username
  password: password
  database: asq_queries
#database:
#  adapter: postgres
#  host: localhost
#  user: username
#  database: asq_queries
#database:
#  adapter: sqlite
#  database: asq_queries

login:
  user: 'root'
  pass: 'default'
misc:
  defaultDb: false # the DB that will be selected by default
  dblistMatch: false # bool false or string with regex to filter databases.